spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/progether?serverTimezone=Asia/Seoul
    username: jcw
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        show_sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
    #    org.apache.coyote.http11: debug
    com.woopaca.progether: info

server:
  port: 8888